baseURL = "https://votresite.netlify.app/"
languageCode = "fr-fr"
title = "Global Study"

[params]
  description = "Bourses, visas et emplois pour la jeunesse africaine"
  contact_email = "contacts.globalstudy@gmail.com"
  admin_name = "Luckman10"
  whatsapp = "+33753883652"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
